### ISSUE TITLE
Implement excel file generator with openpyxl

### ISSUE THREAD

**Issue by gray-adeyi** [gray-adeyi/orderlie-be#7]

**Comment by Malay-dev** [comment]
Hey I would like to work on this issue, Please assign it to me.

**Comment by gray-adeyi** [comment]
Yeah sure. it basically has to be multipurpose so it can be used in different parts of the project. Happy contributing!

**Comment by Malay-dev** [comment]
Hey, I just made this PR for the issue but am confused about How I can test it out.

**Comment by Malay-dev** [comment]
Thank you @gray-adeyi... It was a great pleasure contributing to this project...:innocent:
